// This file is generated by QHNetWorkApiGenerator
// And will be overwritten everytime.
// DO NOT MODIFY!

#import "QHNetworkSampleCustom.h"

NS_ASSUME_NONNULL_BEGIN

@interface QHNetworkSampleCustom (gen)

QH_NETWORK_API_DECL(QHNetworkSampleCustom, QHNetworkSampleCustomResult);

@end

@interface QHNetworkSampleCustomResult (gen)

QH_NETWORK_API_RESULT_DECL(QHNetworkSampleCustom, QHNetworkSampleCustomResult);

@end

NS_ASSUME_NONNULL_END
