// This file is generated by QHNetWorkApiGenerator
// And will be overwritten everytime.
// DO NOT MODIFY!

#import "QHNetworkSampleCustom.h"

NS_ASSUME_NONNULL_BEGIN

@implementation QHNetworkSampleCustom (gen)

QH_NETWORK_API_IMPL_INDIRECT(QHNetworkSampleCustom, QHNetworkSampleCustomResult,
                             QHNetworkJsonApi, QHNetworkJsonApiResult);

@end

@implementation QHNetworkSampleCustomResult (gen)

QH_NETWORK_API_RESULT_IMPL_SUPER(QHNetworkSampleCustom, QHNetworkSampleCustomResult)
{
    [self p_parse:result
         response:response
            error:error
              api:api _QHNetworkSampleCustom:0];
}
QH_NETWORK_API_RESULT_IMPL_RETURN;

@end

NS_ASSUME_NONNULL_END
