// This file is generated by QHNetWorkApiGenerator
// And will not be overwritten if it has alreday exists
// Add your code here

#import <QHCoreLib/QHCoreLib.h>
#import "QHNetworkSampleCustom.h"

@interface QHNetworkSamplePost : QHNetworkSampleCustom

- (instancetype)init;

@end

@interface QHNetworkSamplePostResult : QHNetworkSampleCustomResult

+ (void)p_parse:(QHNetworkSamplePostResult *)result
       response:(QHNetworkResponse *)response
          error:(NSError *__autoreleasing *)error
            api:(QHNetworkSamplePost *)api _QHNetworkSamplePost:(int)notUsed;

@end

#import "QHNetworkSamplePost+gen.h"
