// This file is generated by QHNetWorkApiGenerator
// And will not be overwritten if it has alreday exists
// Add your code here

#import "QHNetworkSamplePost.h"

@implementation QHNetworkSamplePost

- (instancetype)init
{
    self = [super initWithUrl:@"https://httpbin.org/post"
                    queryDict:nil
                     bodyDict:@{}];
    if (self) {

    }
    return self;
}

@end

@implementation QHNetworkSamplePostResult

+ (void)p_parse:(QHNetworkSamplePostResult *)result
       response:(QHNetworkResponse *)response
          error:(NSError *__autoreleasing *)error
            api:(QHNetworkSamplePost *)api _QHNetworkSamplePost:(int)notUsed
{

}

@end
