// This file is generated by QHNetWorkApiGenerator
// And will not be overwritten if it has alreday exists
// Add your code here

#import "QHNetworkSampleGet.h"

@implementation QHNetworkSampleGet

- (instancetype)init
{
    return [super initWithUrl:@"https://httpbin.org/get/" queryDict:@{}];
}

@end

@implementation QHNetworkSampleGetResult

+ (void)p_parse:(QHNetworkSampleGetResult *)result
       response:(QHNetworkResponse *)response
          error:(NSError *__autoreleasing *)error
            api:(QHNetworkSampleGet *)api _QHNetworkSampleGet:(int)notUsed
{

}

@end
