// This file is generated by QHNetWorkApiGenerator
// And will be overwritten everytime.
// DO NOT MODIFY!

#import "QHNetworkSamplePost.h"

NS_ASSUME_NONNULL_BEGIN

@implementation QHNetworkSamplePost (gen)

QH_NETWORK_API_IMPL_INDIRECT(QHNetworkSamplePost, QHNetworkSamplePostResult,
                             QHNetworkJsonApi, QHNetworkJsonApiResult);

@end

@implementation QHNetworkSamplePostResult (gen)

QH_NETWORK_API_RESULT_IMPL_SUPER(QHNetworkSamplePost, QHNetworkSamplePostResult)
{
    [self p_parse:result
         response:response
            error:error
              api:api _QHNetworkSamplePost:0];
}
QH_NETWORK_API_RESULT_IMPL_RETURN;

@end

NS_ASSUME_NONNULL_END
