// This file is generated by QHNetWorkApiGenerator
// And will not be overwritten if it has alreday exists
// Add your code here

#import <QHCoreLib/QHCoreLib.h>
#import "QHNetworkSampleCustom.h"

@interface QHNetworkSampleGet : QHNetworkSampleCustom

- (instancetype)init;

@end

@interface QHNetworkSampleGetResult : QHNetworkSampleCustomResult

+ (void)p_parse:(QHNetworkSampleGetResult *)result
       response:(QHNetworkResponse *)response
          error:(NSError *__autoreleasing *)error
            api:(QHNetworkSampleGet *)api _QHNetworkSampleGet:(int)notUsed;

@end

#import "QHNetworkSampleGet+gen.h"
