// This file is generated by QHNetWorkApiGenerator
// And will be overwritten everytime.
// DO NOT MODIFY!

#import "QHNetworkSamplePost.h"

NS_ASSUME_NONNULL_BEGIN

@interface QHNetworkSamplePost (gen)

QH_NETWORK_API_DECL(QHNetworkSamplePost, QHNetworkSamplePostResult);

+ (instancetype)request_with_query1:(NSString *)query1
                             query2:(NSString *)query2
                              body1:(NSString *)body1
                              bdoy2:(NSString *)bdoy2;

@end

@interface QHNetworkSamplePostResult (gen)

QH_NETWORK_API_RESULT_DECL(QHNetworkSamplePost, QHNetworkSamplePostResult);

@end

NS_ASSUME_NONNULL_END
