// This file is generated by QHNetWorkApiGenerator
// And will not be overwritten if it has alreday exists
// Add your code here

#import "QHNetworkSampleGet.h"

@implementation QHNetworkSampleGet

- (instancetype)init
{
    self = [super initWithUrl:@"https://httpbin.org/get"
                    queryDict:@{}];
    if (self) {

    }
    return self;
}

@end

@implementation QHNetworkSampleGetResult

+ (void)p_parse:(QHNetworkSampleGetResult *)result
       response:(QHNetworkResponse *)response
          error:(NSError *__autoreleasing *)error
            api:(QHNetworkSampleGet *)api _QHNetworkSampleGet:(int)notUsed
{

}

@end
