// This file is generated by QHNetWorkApiGenerator
// And will be overwritten everytime.
// DO NOT MODIFY!

#import "QHNetworkSampleGet.h"

NS_ASSUME_NONNULL_BEGIN

@implementation QHNetworkSampleGet (gen)

QH_NETWORK_API_IMPL_INDIRECT(QHNetworkSampleGet, QHNetworkSampleGetResult,
                             QHNetworkSampleCustom, QHNetworkSampleCustomResult);

@end

@implementation QHNetworkSampleGetResult (gen)

QH_NETWORK_API_RESULT_IMPL_SUPER(QHNetworkSampleGet, QHNetworkSampleGetResult)
{
    [self p_parse:result
         response:response
            error:error
              api:api _QHNetworkSampleGet:0];
}
QH_NETWORK_API_RESULT_IMPL_RETURN;

@end

NS_ASSUME_NONNULL_END
