// This file is generated by QHNetWorkApiGenerator
// And will not be overwritten if it has alreday exists
// Add your code here

#import "QHNetworkSampleCustom.h"

@implementation QHNetworkSampleCustom

- (instancetype)init
{
    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"https://httpbin.org/get"]];

    self = [super initWithUrlRequest:request];
    if (self) {

    }
    return self;
}

@end

@implementation QHNetworkSampleCustomResult

+ (void)p_parse:(QHNetworkSampleCustomResult *)result
       response:(QHNetworkResponse *)response
          error:(NSError *__autoreleasing *)error
            api:(QHNetworkSampleCustom *)api _QHNetworkSampleCustom:(int)notUsed
{

}

@end
