// This file is generated by QHNetWorkApiGenerator
// And will not be overwritten if it has alreday exists
// Add your code here

#import <QHCoreLib/QHCoreLib.h>
#import "QHNetworkSampleApi.h"

NS_ASSUME_NONNULL_BEGIN

@interface QHNetworkSamplePost : QHNetworkSampleApi

@end

@interface QHNetworkSamplePostResult : QHNetworkSampleApiResult

+ (void)p_parse:(QHNetworkSamplePostResult *)result
       response:(QHNetworkResponse *)response
          error:(NSError *__autoreleasing *)error
            api:(QHNetworkSamplePost *)api _QHNetworkSamplePost:(int)notUsed;

@end

NS_ASSUME_NONNULL_END

#import "QHNetworkSamplePost+gen.h"
