// This file is generated by QHNetWorkApiGenerator
// And will be overwritten everytime.
// DO NOT MODIFY!

#import "QHNetworkSampleGet.h"

NS_ASSUME_NONNULL_BEGIN

@interface QHNetworkSampleGet (gen)

QH_NETWORK_API_DECL(QHNetworkSampleGet, QHNetworkSampleGetResult);

@end

@interface QHNetworkSampleGetResult (gen)

QH_NETWORK_API_RESULT_DECL(QHNetworkSampleGet, QHNetworkSampleGetResult);

@end

NS_ASSUME_NONNULL_END
