// This file is generated by QHNetWorkApiGenerator
// And will be overwritten everytime.
// DO NOT MODIFY!

#import "QHNetworkSampleApi.h"

NS_ASSUME_NONNULL_BEGIN

@interface QHNetworkSampleApi (gen)

QH_NETWORK_API_DECL(QHNetworkSampleApi, QHNetworkSampleApiResult);

+ (instancetype)request;

@end

@interface QHNetworkSampleApiResult (gen)

QH_NETWORK_API_RESULT_DECL(QHNetworkSampleApi, QHNetworkSampleApiResult);

@end

NS_ASSUME_NONNULL_END
