// This file is generated by QHNetWorkApiGenerator
// And will not be overwritten if it has alreday exists
// Add your code here

#import "QHNetworkJsonApi.h"

@interface QHNetworkSampleGet : QHNetworkJsonApi

- (instancetype)init;

@end

@interface QHNetworkSampleGetResult : QHNetworkJsonApiResult

+ (void)p_parse:(QHNetworkSampleGetResult *)result
       response:(QHNetworkResponse *)response
          error:(NSError *__autoreleasing *)error
            api:(QHNetworkSampleGet *)api _QHNetworkSampleGet:(int)notUsed;

@end

#import "QHNetworkSampleGet+gen.h"
