// This file is generated by QHNetWorkApiGenerator
// And will be overwritten everytime.
// DO NOT MODIFY!

#import "QHNetworkSamplePost.h"

NS_ASSUME_NONNULL_BEGIN

@interface QHNetworkSamplePost (gen)

QH_NETWORK_API_DECL(QHNetworkSamplePost, QHNetworkSamplePostResult);

@end

@interface QHNetworkSamplePostResult (gen)

QH_NETWORK_API_RESULT_DECL(QHNetworkSamplePost, QHNetworkSamplePostResult);

@end

NS_ASSUME_NONNULL_END
